"""initial

Revision ID: a20be5ad8715
Revises: 
Create Date: 2025-06-30 00:21:50.731658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a20be5ad8715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tuition_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('food_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transport_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diary_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admission_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=True))
        batch_op.alter_column('text_books_fee',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('exercise_books_fee',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('assesment_tool_fee',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('food')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('assesment_tool_fee',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('exercise_books_fee',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('text_books_fee',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.drop_column('balance')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('total_fee')
        batch_op.drop_column('admission_fee')
        batch_op.drop_column('diary_fee')
        batch_op.drop_column('activity_fee')
        batch_op.drop_column('transport_fee')
        batch_op.drop_column('food_fee')
        batch_op.drop_column('tuition_fee')

    # ### end Alembic commands ###
