"""added fe columns

Revision ID: b6cacb14b070
Revises: a20be5ad8715
Create Date: 2025-06-30 12:48:11.394028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cacb14b070'
down_revision = 'a20be5ad8715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_no', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['admission_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('admission_no')

    # ### end Alembic commands ###
